### ISSUE TITLE
Tmux-like Session support.

### ISSUE THREAD

**Issue by mckaygerhard** [moonsteal/moonterm#1]
This terminal is like any VTE terminal, so at least I will request a great feature: "session support", The session support is in two types... 
* with a desktop (we don't like systemd-dependencies so discarded...).
* its own session management, like what Tmux does

the problem with Tmux is that it is console-only, way too old school, so deprecated inclusively that it doesn't integrate with the mouse, and its keyboard shortcuts cause conflicts with working fast and agile in different environments... 

when making a direct **support of moonterm sessions...** we would not have this problem, if the terminal closes when reopening it continues where it left off... according to the configured (no GUI to configure... edit the file or use command line...)

**Comment by darltrash** [comment]
I really like this idea and we are looking forward to implement it, but could you remove the capture please? it may become controversial among other people that could look into our organization.

**Comment by eylles** [comment]
Wouldn't it be better to imolement tmux control mode instead of teinventing the wheel?

No seria mejor implementar tmux control mode en vez de reinventar la rueda?

**Comment by sodomon2** [comment]
I think this would not be necessary, I say this because the moonterm has the option to load any shell, language interpreter, etc., so, I think the most logical thing would be to simply use the tmux shell instead of reinventing the wheel.

So, I think this is no longer something to keep in mind.

**Comment by eylles** [comment]
I still think a vte terminal supporting control mode to render the tmux panes and "windows" (tabs in reality) with gtk widgets would be quite the hit, specially with the upcoming tmux supporting sixel and vte adding sixel support soon tm (a sixel branch works but got jank, tho xfce terminal somehow added sixel support and that one uses vte too).

Still that's just my opinion.

**Comment by sodomon2** [comment]
> I still think a vte terminal supporting control mode to render the tmux panes and "windows" (tabs in reality) with gtk widgets would be quite the hit, specially with the upcoming tmux supporting sixel and vte adding sixel support soon tm (a sixel branch works but got jank, tho xfce terminal somehow added sixel support and that one uses vte too).
> 
> Still that's just my opinion.

What do you mean?

I've never really used tmux, so I don't really know what you mean.

**Comment by mckaygerhard** [comment]
> > I still think a vte terminal supporting control mode to render the tmux panes and "windows" (tabs in reality) with gtk widgets would be quite the hit, specially with the upcoming tmux supporting sixel and vte adding sixel support soon tm (a sixel branch works but got jank, tho xfce terminal somehow added sixel support and that one uses vte too).
> > Still that's just my opinion.
> 
> What do you mean?
> 
> I've never really used tmux, so I don't really know what you mean.

maybe he feels that closed the ticket due to lack of vision... I, a mocosoft hater, don't use mocosoft but I know everything about mocosoft very well... when you haven't used it it's clear that you don't understand what he explains to you but I'm trying to summarize it. with just a few words in a single sentence: better integration and support with (for example) tmux

**Comment by eylles** [comment]
i don't like to be pushy, but i got a good example.

maybe you know [terminator](https://github.com/gnome-terminator/terminator) a gtk + vte terminal that got tabs and can also split "panes", one of it's forks got tmux control mode implemented, here's a [video](https://www.youtube.com/watch?v=DENTRJ_JbTk)

tmux itself got panes and tabs, so the idea of implementing control mode is to use the terminal's native tabs and panes then let users use the tmux features such as copy mode, history search and the most important sessions.

is not really necessary for any terminal that implements tabs, panes or history search like iterm2 to implement tmux control mode, but it is certainly appreciated by users as it provides better integration and consistent user interface.

**Comment by sodomon2** [comment]
> i don't like to be pushy, but i got a good example.
> 
> maybe you know [terminator](https://github.com/gnome-terminator/terminator) a gtk + vte terminal that got tabs and can also split "panes", one of it's forks got tmux control mode implemented, here's a [video](https://www.youtube.com/watch?v=DENTRJ_JbTk)
> 
> tmux itself got panes and tabs, so the idea of implementing control mode is to use the terminal's native tabs and panes then let users use the tmux features such as copy mode, history search and the most important sessions.
> 
> is not really necessary for any terminal that implements tabs, panes or history search like iterm2 to implement tmux control mode, but it is certainly appreciated by users as it provides better integration and consistent user interface.

I don't know if I will be able to implement it, since lgi has crashes with spawn_async (reason why I haven't supported new tabs).

So I'm not sure if this can be implemented using lgi.

Also VTE has some bugs with lgi (another reason why there are things I have not been able to add).
